### ISSUE TITLE
Dependency on deprecated SAML1 classes

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp-module-casserver#32]
Hi @pradtke,

We've been working on SSP 2.0 for a while and this weekend we have removed a lot of deprecated code, including `\SimpleSAML\XML\Shib13\AuthnResponse`..  I didn't realize CAS server relies on these classes..
I don't use the module myself, so I'm not sure what the impact of this is.. I can fix this by moving the classes into this module, but should we really rely on SAML1 in the first place?

**Comment by pradtke** [comment]
Ellucian Banner, a popular ERP system in the US, requires it. It's a weird part of the CAS spec where a ticket can be exchanged for an SAML1 assertion. I _think_  the samlValidate endpoint only makes use of a small part of the SAML1 code. Perhaps we can just copy those necessary classes instead of all the SAML1 stuff? Or maybe there is even more simplification that can be done (e.g. Have an xml template that we replace some values in)?  How about you can copy the classes in for the short term, and I can do the simplification when I have more spare time?

**Comment by tvdijen** [comment]
Gotcha!

**Comment by tvdijen** [comment]
Took care of importing the class and everything else to make the module ready for SSP 2.0..
I'm not sure why the tests fail though.. You think you can help me out with that?
