### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by sudoman** [simplesamlphp/simplesamlphp-module-casserver#33]
I'm excited about trying out the `casserver` module, but I'm having trouble configuring (and enabling?) it.

* Where should `module_casserver.php` go? In the `config` dir?
* Do I need to write a file for the `metadata` directory?
* What URLs or parts of the web interface should I check to use this module?

`/cas/login` returns a 404 for me now, so I must be doing something wrong.

My guess is that knowing more about SimpleSAMLphp would help, but it would be great if your module could also target beginners.

Thanks! : )

**Comment by tvdijen** [comment]
I'm not familiar with this specific module, so I can't really help with that.. But yes, the `module_casserver.php`-file should go into the `config`-directory and the url's would be `https://<your-domain>/<basepath-from-config>/module.php/casserver/login.php` or instead of login.php any other file from the www-directory.

**Comment by sudoman** [comment]
Thanks, that was certainly helpful! : ) I'm sure that I'll have more questions when I work on this next week.

**Comment by tvdijen** [comment]
No problem, but please send your questions to our [mailing list](http://groups.google.com/group/simplesamlphp) instead.
